# Generated by Django 5.2.7 on 2025-10-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('opt_a', models.CharField(max_length=240)),
                ('opt_b', models.CharField(max_length=240)),
                ('opt_c', models.CharField(max_length=240)),
                ('opt_d', models.CharField(max_length=240)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
            ],
        ),
    ]
